In [27]:
import pandas as pd

In [28]:
data = pd.read_csv("C:\\Users\\raghu\\Downloads\\logs_dataset.csv")

In [29]:
data.head()

                    @timestamp                   _id  ip_address
0  July 8th 2019, 14:43:03.000  XswJ0msBoTGddM7vxMDB  10.1.1.285
1  July 8th 2019, 14:43:01.000  dKQJ0msB7mP0GwVzvJjz  10.1.2.389
2  July 8th 2019, 14:42:59.000  CcwJ0msBoTGddM7vtb8y  10.1.1.415
3  July 8th 2019, 14:42:57.000  bKQJ0msB7mP0GwVzrZdT   10.1.1.79
4  July 8th 2019, 14:42:55.000  L6QJ0msB7mP0GwVzpZeI   10.1.1.60

In [30]:
data.shape

(721547, 3)

In [31]:
data.isnull().sum()

@timestamp    0
_id           0
ip_address    0
dtype: int64

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 721547 entries, 0 to 721546
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   @timestamp  721547 non-null  object
 1   _id         721547 non-null  object
 2   ip_address  721547 non-null  object
dtypes: object(3)
memory usage: 16.5+ MB

In [33]:
data.groupby("ip_address")["_id"].count()

ip_address
10.1.1.1      1446
10.1.1.100    2860
10.1.1.101    1465
10.1.1.106    1408
10.1.1.109    1459
              ...
10.1.2.86     4307
10.1.2.89     2826
10.1.2.90     2904
10.1.2.95     2868
10.1.2.99     1423
Name: _id, Length: 386, dtype: int64

In [34]:
data['@timestamp'] = (
    data['@timestamp']
    .str.replace(r'(\d+)(st|nd|rd|th)', r'\1', regex=True)
)
data['@timestamp'] = pd.to_datetime(
    data['@timestamp'],
    format='%B %d %Y, %H:%M:%S.%f'
)

In [36]:
data.sort_values(['ip_address', '@timestamp'], inplace=True)

In [37]:
data.head()

                @timestamp                   _id ip_address
721473 2019-06-09 00:06:09  DBuOOWsB7mP0GwVzhZ9U   10.1.1.1
720483 2019-06-09 01:28:39  bB7aOWsB7mP0GwVzDY5G   10.1.1.1
719233 2019-06-09 03:12:49  R0w5OmsBoTGddM7vayZT   10.1.1.1
719222 2019-06-09 03:13:45  U0w6OmsBoTGddM7vRi8R   10.1.1.1
718875 2019-06-09 03:42:39  z01UOmsBoTGddM7vuzyC   10.1.1.1

In [38]:
data['shift_time'] = data.groupby(['ip_address'])['@timestamp'].shift(1)

In [39]:
data.head()

,@timestamp,_id,ip_address,shift_time
721473,2019-06-09 00:06:09,DBuOOWsB7mP0GwVzhZ9U,10.1.1.1,NaT
720483,2019-06-09 01:28:39,bB7aOWsB7mP0GwVzDY5G,10.1.1.1,2019-06-09 00:06:09
719233,2019-06-09 03:12:49,R0w5OmsBoTGddM7vayZT,10.1.1.1,2019-06-09 01:28:39
719222,2019-06-09 03:13:45,U0w6OmsBoTGddM7vRi8R,10.1.1.1,2019-06-09 03:12:49
718875,2019-06-09 03:42:39,z01UOmsBoTGddM7vuzyC,10.1.1.1,2019-06-09 03:13:45

In [40]:
data['time_diff'] = (data['@timestamp']-data['shift_time']).dt.seconds//60

In [41]:
data.head()

,@timestamp,_id,ip_address,shift_time,time_diff
721473,2019-06-09 00:06:09,DBuOOWsB7mP0GwVzhZ9U,10.1.1.1,NaT,NaN
720483,2019-06-09 01:28:39,bB7aOWsB7mP0GwVzDY5G,10.1.1.1,2019-06-09 00:06:09,82.0
719233,2019-06-09 03:12:49,R0w5OmsBoTGddM7vayZT,10.1.1.1,2019-06-09 01:28:39,104.0
719222,2019-06-09 03:13:45,U0w6OmsBoTGddM7vRi8R,10.1.1.1,2019-06-09 03:12:49,0.0
718875,2019-06-09 03:42:39,z01UOmsBoTGddM7vuzyC,10.1.1.1,2019-06-09 03:13:45,28.0

In [43]:
data['date'] = data['@timestamp'].dt.date

In [45]:
data['weekday'] = data['@timestamp'].dt.weekday

In [47]:
data['hour'] = data['@timestamp'].dt.hour

In [48]:
data['is_weekend'] = ((data['weekday'] == 5) | (data['weekday'] == 6)).astype(int)

In [49]:
data.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date,weekday,hour,is_weekend
721473,2019-06-09 00:06:09,DBuOOWsB7mP0GwVzhZ9U,10.1.1.1,NaT,NaN,2019-06-09,6,0,1
720483,2019-06-09 01:28:39,bB7aOWsB7mP0GwVzDY5G,10.1.1.1,2019-06-09 00:06:09,82.0,2019-06-09,6,1,1
719233,2019-06-09 03:12:49,R0w5OmsBoTGddM7vayZT,10.1.1.1,2019-06-09 01:28:39,104.0,2019-06-09,6,3,1
719222,2019-06-09 03:13:45,U0w6OmsBoTGddM7vRi8R,10.1.1.1,2019-06-09 03:12:49,0.0,2019-06-09,6,3,1
718875,2019-06-09 03:42:39,z01UOmsBoTGddM7vuzyC,10.1.1.1,2019-06-09 03:13:45,28.0,2019-06-09,6,3,1

In [51]:
data['hour_bucket'] = data['hour']//4
# This integer division by 4, so we can analyse 4-hour buckets instead of every single hour

In [52]:
ip_addr ='ip_address'

In [54]:
ip_counts = data.groupby(ip_addr)['@timestamp'].count().reset_index()

In [55]:
ip_counts.head()

   ip_address  @timestamp
0    10.1.1.1        1446
1  10.1.1.100        2860
2  10.1.1.101        1465
3  10.1.1.106        1408
4  10.1.1.109        1459

In [56]:
ip_counts = ip_counts.rename(columns={'@timestamp':'total_count'})

In [58]:
daily_counts = data.groupby([ip_addr,'date'])['@timestamp'].count().reset_index()

In [60]:
daily_counts = daily_counts.rename(columns={'@timestamp':'daily_counts'})

In [61]:
daily_counts_avg = daily_counts.groupby(ip_addr).daily_counts.median().reset_index()

In [62]:
daily_counts_avg.head(5)

   ip_address  daily_counts
0    10.1.1.1          40.0
1  10.1.1.100          78.0
2  10.1.1.101          40.0
3  10.1.1.106          35.5
4  10.1.1.109          42.5

In [64]:
weekend_counts = data.groupby([ip_addr, 'is_weekend'])['@timestamp'].count().reset_index()

In [65]:
weekend_counts

     ip_address  is_weekend  @timestamp
0      10.1.1.1           0         975
1      10.1.1.1           1         471
2    10.1.1.100           0        1960
3    10.1.1.100           1         900
4    10.1.1.101           0        1006
..          ...         ...         ...
767   10.1.2.90           1         871
768   10.1.2.95           0        1973
769   10.1.2.95           1         895
770   10.1.2.99           0         978
771   10.1.2.99           1         445

[772 rows x 3 columns]